//the connection with firebase happens in this file

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSbVdMi3m--JuRtqTSc6Arv2qs_DWDOZw',
    appId: '1:1054161917041:web:277022cbefe8d94a63f7d0',
    messagingSenderId: '1054161917041',
    projectId: 'evey-00',
    authDomain: 'evey-00.firebaseapp.com',
    storageBucket: 'evey-00.appspot.com',
    measurementId: 'G-HX7N2T9DFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPmS1CgyoRAky2Chn_IdkNrReWViCkfFc',
    appId: '1:1054161917041:android:1ce6161d8559da7963f7d0',
    messagingSenderId: '1054161917041',
    projectId: 'evey-00',
    storageBucket: 'evey-00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA77lRB5V0Ahx67WoAiSKvH-v_3EkOwzF4',
    appId: '1:1054161917041:ios:e9369655f4d4ecb563f7d0',
    messagingSenderId: '1054161917041',
    projectId: 'evey-00',
    storageBucket: 'evey-00.appspot.com',
    iosClientId:
        '1054161917041-6c79vl4gtuu3m9p5armndqbbpelqmra4.apps.googleusercontent.com',
    iosBundleId: 'com.example.evey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA77lRB5V0Ahx67WoAiSKvH-v_3EkOwzF4',
    appId: '1:1054161917041:ios:e9369655f4d4ecb563f7d0',
    messagingSenderId: '1054161917041',
    projectId: 'evey-00',
    storageBucket: 'evey-00.appspot.com',
    iosClientId:
        '1054161917041-6c79vl4gtuu3m9p5armndqbbpelqmra4.apps.googleusercontent.com',
    iosBundleId: 'com.example.evey',
  );
}
